# fly.toml app configuration file generated for muddy-wave-2193 on 2023-06-23T16:36:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muddy-wave-2193"
primary_region = "waw"

PORT = "3001" # add this

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
